# Generated by Django 6.0 on 2025-12-05 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название скидки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('discount_type', models.CharField(choices=[('percent', 'Процентная скидка'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=10, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, help_text='Процент (0-100) или фиксированная сумма', max_digits=10, verbose_name='Значение скидки')),
                ('apply_to', models.CharField(choices=[('category', 'Категория'), ('product', 'Товар'), ('variant', 'Вариант товара')], max_length=10, verbose_name='Применяется к')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Чем выше число, тем выше приоритет (применяется первым)', verbose_name='Приоритет')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='catalog.category', verbose_name='Категория')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='catalog.product', verbose_name='Товар')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='catalog.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['-priority', '-start_date'],
            },
        ),
    ]
