# Generated by Django 6.0 on 2025-12-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('subject', models.CharField(blank=True, choices=[('question', 'Вопрос о товаре'), ('order', 'Вопрос о заказе'), ('delivery', 'Доставка'), ('warranty', 'Гарантия и возврат'), ('other', 'Другое')], max_length=50, verbose_name='Тема обращения')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('source_url', models.CharField(blank=True, max_length=500, verbose_name='Источник (URL)')),
            ],
            options={
                'verbose_name': 'Сообщение с формы контактов',
                'verbose_name_plural': 'Сообщения с формы контактов',
                'ordering': ['-created_at'],
            },
        ),
    ]
