# Generated by Django 6.0 on 2025-12-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_line_order_city_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес доставки'),
        ),
    ]
