# Generated by Django 6.0 on 2026-03-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_access_token',
            field=models.CharField(blank=True, help_text='Ссылка с этим токеном позволяет гостю просматривать заказ без входа.', max_length=64, null=True, unique=True, verbose_name='Токен доступа (гостевой заказ)'),
        ),
    ]
