# Generated by Django 6.0 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_add_guest_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("changed_mind", "Передумал(а) покупать"),
                    ("found_better", "Нашел(а) более подходящий вариант"),
                    ("delivery_time", "Не устраивают сроки доставки"),
                    ("order_mistake", "Ошибся(лась) при оформлении"),
                    ("payment_issue", "Возникли сложности с оплатой"),
                    ("other", "Другая причина"),
                ],
                max_length=32,
                verbose_name="Причина отмены",
            ),
        ),
    ]
